---
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
rules:
  react/react-in-jsx-scope: off
  import/order:
    - error
    - groups:
        - [builtin, external]
        - internal
        - sibling
        - parent
        - index
settings:
  react:
    version: detect
